name: WifiPulse
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.5.3
  syncfusion_flutter_gauges: ^30.1.38
  flutter_network_speed_test: ^0.1.5
  geolocator: ^14.0.2
  network_info_plus: ^6.1.4
  flutter_map: ^7.0.0
  flutter_map_heatmap: ^0.0.8
  latlong2: ^0.9.1
  supabase_flutter: ^2.10.3
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  path_provider: ^2.1.5
  osm_nominatim: ^3.0.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/icons/logo.png

  fonts:
    - family: GreycliffCF
      fonts:
        - asset: assets/fonts/fonnts.com-Greycliff_CF_Bold.otf
        - asset: assets/fonts/fonnts.com-Greycliff_CF_Regular.otf
          weight: 700

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/logo.png"